### ISSUE TITLE
运行失败，提示js_url不存在

### ISSUE THREAD

**Issue by mntn0x** [Threezh1/JSFinder#7]
在windows10和kali下运行`python3 JSFinder.py -u https://www.jd.com`均提示如下：
```
url:https://www.jd.com
Traceback (most recent call last):
  File "JSFinder.py", line 242, in <module>
    urls = find_by_url(args.url)
  File "JSFinder.py", line 124, in find_by_url
    temp_urls = extract_URL(script_array[script])
  File "JSFinder.py", line 50, in extract_URL
    return [match.group().strip('"').strip("'") for match in result
  File "JSFinder.py", line 51, in <listcomp>
    if match.group() not in js_url]
NameError: name 'js_url' is not defined
```
能帮忙解决一下嘛？

**Comment by Threezh1** [comment]
已经恢复好了。你重新下载一下。
